-- Create cart table
create table if not exists cart (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  product_id bigint references products(id) not null,
  quantity integer default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table cart enable row level security;

-- Policies
create policy "Users can view their own cart"
  on cart for select
  using ( auth.uid() = user_id );

create policy "Users can insert into their own cart"
  on cart for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own cart"
  on cart for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own cart"
  on cart for delete
  using ( auth.uid() = user_id );

-- IMPORTANT: Foreign key setup for the join to work
-- Ensure the foreign key is explicitly named or standard so PostgREST can find it.
-- The above "product_id references products(id)" is usually enough.
