-- Add model_url and color columns to products table if they don't exist
ALTER TABLE products ADD COLUMN IF NOT EXISTS model_url TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS color TEXT;

-- Add model_url to users table if it doesn't exist
ALTER TABLE users ADD COLUMN IF NOT EXISTS model_url TEXT;

-- Create Wishlist table if it doesn't exist (part of the same update block usually)
CREATE TABLE IF NOT EXISTS wishlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  UNIQUE(user_id, product_id)
);

-- Enable RLS for Wishlist
ALTER TABLE wishlist ENABLE ROW LEVEL SECURITY;

-- Wishlist Policies
DROP POLICY IF EXISTS "Users can view own wishlist" ON wishlist;
CREATE POLICY "Users can view own wishlist"
ON wishlist FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can add to own wishlist" ON wishlist;
CREATE POLICY "Users can add to own wishlist"
ON wishlist FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete from own wishlist" ON wishlist;
CREATE POLICY "Users can delete from own wishlist"
ON wishlist FOR DELETE
TO authenticated
USING (auth.uid() = user_id);
