-- Update products table to support multiple images and description
ALTER TABLE products ADD COLUMN IF NOT EXISTS images TEXT[] DEFAULT '{}';
ALTER TABLE products ADD COLUMN IF NOT EXISTS description TEXT DEFAULT 'No description available for this product.';

-- Create reviews table
CREATE TABLE IF NOT EXISTS product_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  comment TEXT
);

-- Enable RLS for reviews
ALTER TABLE product_reviews ENABLE ROW LEVEL SECURITY;

-- Reviews Policies
CREATE POLICY "Public Read Reviews"
ON product_reviews FOR SELECT
USING (true);

CREATE POLICY "Authenticated Users Insert Reviews"
ON product_reviews FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users Update Own Reviews"
ON product_reviews FOR UPDATE
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users Delete Own Reviews"
ON product_reviews FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- Create product-images bucket
INSERT INTO storage.buckets (id, name, public) VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO NOTHING;

-- Product Images Storage Policies
CREATE POLICY "Public Read Product Images"
ON storage.objects FOR SELECT
USING ( bucket_id = 'product-images' );

CREATE POLICY "Authenticated Admin Upload Product Images"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'product-images' );

CREATE POLICY "Authenticated Admin Update Product Images"
ON storage.objects FOR UPDATE
TO authenticated
USING ( bucket_id = 'product-images' );

CREATE POLICY "Authenticated Admin Delete Product Images"
ON storage.objects FOR DELETE
TO authenticated
USING ( bucket_id = 'product-images' );
